version: "3"
services:
  bootstrap:
    build:
      context: .
    command: "sh -c 'python3 -u src/main.py'"
    ports:
      - 36979:36979
  node:
    build:
      context: .
    depends_on:
      - bootstrap
    deploy:
      replicas: 3
    command: "sh -c 'python3 -u src/main.py --bootstrap_node bootstrap:6501 '"