version: "3"
services:
  bootstrap:
    build:
      context: .
    command: "sh -c 'python3 -u src/main.py'"

  node:
    build:
      context: .
    depends_on:
      - bootstrap
    ports:
      - "8001:8010"
    deploy:
      replicas: 6
    command: "sh -c 'python3 -u src/main.py --bootstrap_node bootstrap:6501 '"